export const selectWaterData = (state) => state.water.waterData;
export const selectDailyData = (state) => state.water.dailyData;
export const selectMonthlyData = (state) => state.water.monthlyData;
export const selectTotalAmount = (state) => state.water.totalAmount;
export const selectSelectedDate = (state) => state.water.selectedDate;
export const selectTotalPercentage = (state) => state.water.totalPercentage;
export const selectIsLoading = (state) => state.water.isLoading;
export const selectIsError = (state) => state.water.isError;
export const selectCurrentItem = (state) => state.contacts.currentItem;
